---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-config
  namespace: django-app
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "admin"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  CSRF_TRUSTED_ORIGINS: "https://<your-domain> "
  ALLOWED_HOSTS: "<your-domain> "